#!/bin/sh

mkdir -p .tmp
rm .tmp/scraperwiki.sqlite
sqlite3 .tmp/scraperwiki.sqlite 'create table `all`(dummy_column)'
out=$(HOME=.tmp PATH_INFO=all ../csv.sh 2>&1)
case $out in
  (*'rror:'*) exit 1;;
  (*'Status: 200'*) exit 0;;
  (*) exit 1;;
esac
